default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: <%= Settings.db.default.username %>
  password: <%= Settings.db.default.password %>
  host: <%= Settings.db.default.host %>
  port: 3306

development:
  <<: *default
  database: fi_chat_development

staging:
  <<: *default
  database: fi_chat_staging

test:
  <<: *default
  database: fi_chat_test

production:
  <<: *default
  database: fi_chat_production
