db:
  default:
    host: <%= ENV['HOST'] %> 
    port: 3306
    username: <%= ENV['USERNAME'] %>
    password: <%= ENV['DATABASE_WRITE_PASSWORD'] %>

aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

requl_mobile:
  api_base_url: <%= ENV['API_URL'] %>]
  application_token: <%= ENV['APPLICATIONT_TOKEN_FOR_REQUL_MOBILE'] %>
